/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

 /* Generated by Cable Build Info on 2022-06-06T16:02:28. Do not modify directly. */

#include "buildinfo.h"

const struct buildinfo* kawpowminer_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_name = "kawpowminer",
        .project_version = "1.2.4+commit.632f6ea0.dirty",
        .project_name_with_version = "kawpowminer-1.2.4+commit.632f6ea0.dirty",
        .git_commit_hash = "632f6ea0a5cd09e2c6443374dbe6db0a767715ba",
        .system_name = "windows",
        .system_processor = "amd64",
        .compiler_id = "msvc",
        .compiler_version = "19.29.30145.0",
        .build_type = "relwithdebinfo",
    };
    return &buildinfo;
}
